matrix:
  include:
  - language: node_js
    node_js:
      - "node"
    deploy:
      - skip_cleanup: true
        provider: script
        script: npm run build && npm run gh-pages
        on:
          branch: master
      - skip_cleanup: true
        provider: script
        script: npm run build && npm run gh-pages -- -p "$TRAVIS_BRANCH"
        on:
          all_branches: true
          condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
  - language: go
    services:
      - docker
    go:
      - 1.12.5
    env:
      - GO111MODULE=on
    install: true
    script:
      - go mod download
      - make test
    before_deploy:
      - make docker-build
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    deploy:
      provider: script
      script: make docker-push
      on:
        branch: master
