# Travis CI (http://travis-ci.org/) is a continuous integration
# service for open source projects.

language: go

services:
  - docker

go:
  - 1.12.5

script:
  - make test

before_install:
  - make docker-build

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: make docker-push
  on:
    branch: master
